### ISSUE TITLE
Device Templates support?

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [iot-for-all/iotc-device-bridge#19]
The other IOTC device bridge (https://github.com/Azure/iotc-device-bridge) supports Device Templates to correctly handle Device data.

Does this project support it also? E.g. will a device be registered in IoT Central application automatically?

I had trouble setting up this project to verify this myself, thus asking in the issue.
Thank you!

**Comment by firedog1024** [comment]
The device will not be registered automatically the Bridge 2.0 provides you with a REST endpoint that you can call to perform actions against the bridge.  These actions you can perform include registration.  This is the swagger for the registration call:

`
    "/devices/{deviceId}/Registration": {
      "post": {
        "tags": [
          "Registration"
        ],
        "summary": "Performs DPS registration for a device, optionally assigning it to a model.",
        "description": "The registration result is internally cached to be used in future connections.\r\nThis route is only intended for ahead-of-time registration of devices with the bridge and assignment to a specific model. To access all DPS registration features,\r\nincluding sending custom registration payload and getting the assigned hub, please use the DPS REST API (https://docs.microsoft.com/en-us/rest/api/iot-dps/).\r\n            \r\n<b>NOTE:</b> DPS registration is a long-running operation, so calls to this route may take a long time to return. If this is a concern, use the DPS REST API directly, which provides\r\nsupport for long-running operation status lookup.",
        "operationId": "Register",
        "consumes": [
          "application/json",
          "text/json",
          "application/*+json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "deviceId",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/RegistrationBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Registration successful."
          }
        }
      }
    },
`

The body of the POST call will contain the registration payload that can include the model id to associate the device with in IoT Central.  For example:

`
{
    "iotcModelId": "< put your model id here >",
}
`

**Comment by peolivei2** [comment]
Adding to the answer above, if you try to send telemetry for a device (or any other operation) without explicitly making the registration call first, the device will just be registered as "unassociated", so you can move it to the correct template later in IoT Central. So, to summarize, you have 3 options for registration:
- **a.** Call the registration endpoint in this bridge passing the correct model then start sending/receiving data (this will register the device in the correct model, as mentioned above).
- **b.** Just start sending/receiving data for the device using this bridge, which will cause the device to be registered as "unassociated". Then manually move it to the right template in IoT Central.
- **c.** Manually create the device in the correct template in IoT Central first, then start sending/receiving data for the device using this bridge.

**Comment by AnatoliiStepaniuk** [comment]
Thanks!
You've answered my question!
