### ISSUE TITLE
Sending data to device via device bridge

### ISSUE THREAD

**Issue by JBischoff1** [iot-for-all/iotc-device-bridge#22]
I can successfully receive messages on my Azure IoT Central application from my device via the device bridge that I created. However, when I try to send data back using a template command, I get the following error:
```
Error
The device was not found when trying to executing the command. Check if it is correctly running and connected.
```
How can I go about fixing this error so that I can send data back to my device? Thanks!

**Comment by peolivei2** [comment]
Before receiving commands, you must [subscribe to method notifications](https://github.com/iot-for-all/iotc-device-bridge#subscribing-to-events) for that specific device in the bridge.

The description of how to subscribe to a method can be found in the [Bridge API swagger](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/iot-for-all/iotc-device-bridge/main/Docs/swagger.json#/Methods/CreateOrUpdateMethodsSubscription). Basically you make a ` PUT` call to `/devices/{deviceId}/Methods/sub`, passing the `callbackUrl` in the body, with the URL that you'd like the Bridge to call when a method/command execution is received for that device.

The Bridge won't receive commands for your device unless a method subscription is active.

**Comment by JBischoff1** [comment]
Okay, I am getting an error because my request is unauthorized. Is there a specific API key that I should use and where can I find it?

**Comment by peolivei2** [comment]
When deploying the Bridge, you specify a custom API key as explained [here](https://github.com/iot-for-all/iotc-device-bridge#33-api-key). That key must be included in the ``x-api-key` header of every request to the Bridge, including the request to send telemetry.

**Comment by JBischoff1** [comment]
Oh okay thanks. That got rid of the error on the Azure application side and it looks like the command sends to the bridge successfully. 
However, the data does not show up on my callback URL. I think this is because my callback URL requires authentication. Is there a way to also pass credentials to the device bridge when sending data?

**Comment by peolivei2** [comment]
It doesn't currently support webhook authentication. You can either use an api key in a query parameter embedded in the callback URL, if your target service supports that (for instance, like Azure Functions), or you can customize the code to add your authentication.

**Comment by JBischoff1** [comment]
Would that require me to implement code for an adapter for the bridge to send data and pass credentials or is there another place to add multiple keys for authentication?

**Comment by JBischoff1** [comment]
What part of the code would I have to modify to add authentication. Is there any documentation on this process?

**Comment by peolivei2** [comment]
You can either add an adapter or change the code directly, both would work. The `Samples` folder contains some examples of adapters and how to deploy them. In the source code, method callbacks are called [here](https://github.com/iot-for-all/iotc-device-bridge/blob/main/DeviceBridge/Services/SubscriptionCallbackFactory.cs#L125).

**Comment by JBischoff1** [comment]
Does the device bridge support basic authentication where the username and password is included in the authentication header?

**Comment by peolivei2** [comment]
No. As I mentioned, to include any form of callback authentication, you need to extend it either through an adapter or directly in the source. The core just calls the provided endpoint directly with the event body.

**Comment by JBischoff1** [comment]
Okay I made changes directly to the code for authentication but I'm still having this problem. I tried to view the logs my log workspace and nothing is there from either device bridge that I was using. Should I be looking somewhere else for the logs from the SubscriptionCallbackFactory file?

**Comment by JBischoff1** [comment]
Thanks for all of your help! I was able to solve this problem so I will be closing the ticket.
